#!/usr/bin/env bash
# DNS plumbing.
#
# The problem
# -----------
# Cloudflare WARP rewrites /etc/resolv.conf to its own loopback resolver:
#
#     # This file was generated by cloudflare-warp.
#     nameserver 127.0.2.2
#     nameserver 127.0.2.3
#
# Those addresses are only meaningful inside the network namespace WARP runs
# in. /etc/resolv.conf, however, lives in the *mount* namespace, so it is one
# shared file for both the root namespace (tailscaled, and everything else in
# the container) and the WARP namespace. The rewrite therefore reaches the root
# namespace, where nothing listens on 127.0.2.2, and DNS dies for tailscaled.
# Turning Tailscale DNS off only hides the symptom.
#
# Why not give each namespace its own /etc/resolv.conf?
# ----------------------------------------------------
# That needs a mount namespace and a bind mount. Docker's default AppArmor
# profile contains a blanket `deny mount,`, so no capability set makes that
# work: `unshare --mount` dies with
#     unshare: cannot change root filesystem propagation: Permission denied
# before it can even set propagation, and bind mounts are denied outright.
# (See https://raw.githubusercontent.com/moby/moby/v27.3.1/profiles/apparmor/template.go)
#
# The fix
# -------
# Make the single shared file correct for BOTH namespaces at once, by making
# every address in it resolvable from either side:
#
#   1. Run a stub resolver in the ROOT namespace bound to WARP's own loopback
#      addresses (127.0.2.2, 127.0.2.3). After WARP rewrites the file, the root
#      namespace resolves through our stub, while the WARP namespace resolves
#      through WARP's proxy -- each namespace has its own loopback, so the two
#      listeners never collide despite the identical address.
#
#   2. Also bind the stub to the veth host address (10.200.0.1), which is the
#      one resolver address reachable from *both* namespaces. Seed
#      /etc/resolv.conf with it before warp-svc starts, so the WARP namespace
#      can resolve during registration, before it installs its own proxy.
#
# Net effect: whichever of those addresses the shared file happens to contain,
# name resolution works in both namespaces, and no mount is ever needed.
# shellcheck shell=bash

set -euo pipefail

# Root-namespace stub resolver.
DNS_STUB_PID=""
DNSMASQ_CONF="${DNSMASQ_CONF:-/etc/cfw2tsen/dnsmasq.conf}"
DNSMASQ_PIDFILE="${DNSMASQ_PIDFILE:-/run/cfw2tsen-dnsmasq.pid}"
DNS_UPSTREAM_FILE="${DNS_UPSTREAM_FILE:-/etc/cfw2tsen/upstream-resolvers.conf}"
# WARP's own resolver addresses. These are fixed constants with no documented
# override: https://developers.cloudflare.com/cloudflare-one/team-and-resources/devices/cloudflare-one-client/configure/route-traffic/client-architecture/
WARP_DNS_V4_A="${WARP_DNS_V4_A:-127.0.2.2}"
WARP_DNS_V4_B="${WARP_DNS_V4_B:-127.0.2.3}"

# A name the stub answers locally, without consulting an upstream resolver.
# Startup and the smoke test use it to prove the stub is actually answering in
# each namespace, without depending on external DNS (which would make CI flaky).
DNS_PROBE_NAME="${DNS_PROBE_NAME:-stub.cfw2tsen.internal}"

# The stub is only needed when WARP is isolated in its own network namespace.
# Without isolation WARP runs in the container's namespace and its own proxy is
# directly reachable, so a stub would just fight it for the same address.
dns_stub_enabled() {
    [ "$(env_bool WARP_ROOT_DNS_STUB 1)" = "1" ] || return 1
    [ -n "${WARP_NETNS:-}" ] || return 1
    [ "${WARP_MODE:-warp}" != "proxy" ] || return 1
    return 0
}

# ---------------------------------------------------------------------------
# Upstream resolvers
# ---------------------------------------------------------------------------

# Remember the resolvers the container was given, because WARP overwrites the
# file that holds them and they are the only route to the outside world for the
# stub. The stub must never forward to WARP's own addresses: that is a loop.
capture_upstream_resolvers() {
    mkdir -p "$(dirname "$DNS_UPSTREAM_FILE")"

    local stub_addr="${VETH_HOST_IP:-10.200.0.1}"
    local found=() ns
    while read -r ns; do
        [ -n "$ns" ] || continue
        # Never forward to ourselves, and never to WARP's namespace-local
        # addresses: either would be a resolution loop.
        case "$ns" in
            "$WARP_DNS_V4_A"|"$WARP_DNS_V4_B"|"$stub_addr") continue ;;
        esac
        found+=("$ns")
    done < <(awk '/^[[:space:]]*nameserver/ {print $2}' /etc/resolv.conf 2>/dev/null || true)

    if [ "${#found[@]}" -eq 0 ]; then
        # Either this is a restart (the file now names our own stub) or the
        # container was given no resolver at all. Reuse the list captured on the
        # previous start before falling back to a public resolver.
        if [ -s "$DNS_UPSTREAM_FILE" ]; then
            log_debug "Reusing the upstream resolvers captured earlier"
            return 0
        fi
        log_warn "No usable upstream resolver in /etc/resolv.conf; falling back to 1.1.1.1"
        found=("1.1.1.1" "1.0.0.1")
    fi

    : > "$DNS_UPSTREAM_FILE"
    local s
    for s in "${found[@]}"; do
        printf '%s\n' "$s" >> "$DNS_UPSTREAM_FILE"
    done
    log_info "Upstream resolvers for the root-namespace stub: ${found[*]}"
}

# ---------------------------------------------------------------------------
# Stub resolver
# ---------------------------------------------------------------------------

write_dnsmasq_config() {
    mkdir -p "$(dirname "$DNSMASQ_CONF")" /var/log/cfw2tsen

    local upstreams=()
    if [ -s "$DNS_UPSTREAM_FILE" ]; then
        mapfile -t upstreams < "$DNS_UPSTREAM_FILE"
    fi
    [ "${#upstreams[@]}" -gt 0 ] || upstreams=("1.1.1.1" "1.0.0.1")

    {
        echo "# Generated by cfw2tsen. Do not edit."
        # Never read /etc/resolv.conf: WARP rewrites it to our own addresses,
        # which would make the stub forward to itself.
        echo "no-resolv"
        echo "bind-interfaces"
        echo "port=53"
        echo "pid-file=${DNSMASQ_PIDFILE}"
        # Stay in the foreground so the PID we record is the process that is
        # actually serving, not a parent that exits as soon as it has forked.
        echo "keep-in-foreground"
        # Everything in this container already runs as root; do not depend on
        # the dnsmasq system user existing in the image.
        echo "user=root"
        echo "cache-size=1000"
        # WARP's loopback addresses: what the shared file contains once WARP
        # has rewritten it. The root namespace needs its own listener here.
        echo "listen-address=${WARP_DNS_V4_A}"
        echo "listen-address=${WARP_DNS_V4_B}"
        # The veth host address: reachable from the WARP namespace too, so it
        # covers the window before WARP installs its own proxy.
        echo "listen-address=${VETH_HOST_IP:-10.200.0.1}"
        # A fixed local answer, so the stub's health can be probed in either
        # namespace without touching an upstream resolver.
        echo "address=/${DNS_PROBE_NAME}/127.0.0.1"
        local s
        for s in "${upstreams[@]}"; do
            [ -n "$s" ] && echo "server=${s}"
        done
    } > "$DNSMASQ_CONF"
}

# Loopback addresses in 127.0.0.0/8 are local to whichever namespace owns the
# loopback device. WARP adds these inside its namespace; the root namespace
# needs its own copy before the stub can bind them.
ensure_loopback_addresses() {
    local addr
    for addr in "$WARP_DNS_V4_A" "$WARP_DNS_V4_B"; do
        if ! ip -4 addr show dev lo 2>/dev/null | grep -qF "${addr}/"; then
            ip addr add "${addr}/32" dev lo 2>/dev/null \
                || log_debug "Could not add ${addr} to lo (it may already be reachable)"
        fi
    done
}

start_root_dns_stub() {
    dns_stub_enabled || { log_debug "Root-namespace DNS stub not required"; return 0; }

    if ! command -v dnsmasq >/dev/null 2>&1; then
        log_error "dnsmasq is not installed; the container's own resolver will break once WARP rewrites /etc/resolv.conf."
        return 1
    fi

    capture_upstream_resolvers
    write_dnsmasq_config
    ensure_loopback_addresses

    # Clear a stale pidfile so dnsmasq does not refuse to start.
    if [ -f "$DNSMASQ_PIDFILE" ]; then
        local stale
        stale="$(cat "$DNSMASQ_PIDFILE" 2>/dev/null || true)"
        if [ -n "$stale" ] && ! kill -0 "$stale" 2>/dev/null; then
            rm -f "$DNSMASQ_PIDFILE"
        fi
    fi

    log_info "Starting root-namespace DNS stub (${WARP_DNS_V4_A}, ${WARP_DNS_V4_B}, ${VETH_HOST_IP:-10.200.0.1})"
    dnsmasq --conf-file="$DNSMASQ_CONF" >>/var/log/cfw2tsen/dnsmasq.log 2>&1 &
    DNS_STUB_PID=$!

    # Prove it answers rather than trusting the fork. The probe name is answered
    # locally, so this measures the stub, not the upstream network.
    local waited=0
    while (( waited < 20 )); do
        if command -v dig >/dev/null 2>&1; then
            dig +time=1 +tries=1 @"$WARP_DNS_V4_A" "$DNS_PROBE_NAME" +short 2>/dev/null | grep -q '127.0.0.1' && break
        elif getent hosts "$DNS_PROBE_NAME" >/dev/null 2>&1; then
            break
        fi
        sleep 0.5
        waited=$(( waited + 1 ))
    done

    if ! kill -0 "$DNS_STUB_PID" 2>/dev/null; then
        log_error "The DNS stub exited immediately. Last log lines:"
        tail -n 20 /var/log/cfw2tsen/dnsmasq.log >&2 2>/dev/null || true
        return 1
    fi

    log_info "Root-namespace DNS stub is up (pid ${DNS_STUB_PID})"
}

stop_root_dns_stub() {
    local pid=""
    if [ -f "$DNSMASQ_PIDFILE" ]; then
        pid="$(cat "$DNSMASQ_PIDFILE" 2>/dev/null || true)"
    fi
    [ -n "$pid" ] || pid="$DNS_STUB_PID"
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
        log_info "Stopping the DNS stub"
        kill -TERM "$pid" 2>/dev/null || true
        wait "$pid" 2>/dev/null || true
    fi
    DNS_STUB_PID=""
}

# ---------------------------------------------------------------------------
# The shared resolv.conf
# ---------------------------------------------------------------------------

# Point the shared file at an address BOTH namespaces can resolve through.
#
# 10.200.0.1 (the veth host side) is reachable from the root namespace as a
# local address and from the WARP namespace over the veth, so it works on both
# sides during the window before WARP installs its own proxy. Once WARP
# rewrites the file to 127.0.2.2/127.0.2.3, the stub started above serves the
# root namespace and WARP's proxy serves its own -- so the file stays valid.
#
# This is the one place that intentionally writes /etc/resolv.conf. It is a
# shared file by necessity, and leaving it pointing at a resolver that exists in
# only one namespace is precisely the bug being fixed.
point_resolv_conf_at_stub() {
    dns_stub_enabled || return 0

    local resolver="${VETH_HOST_IP:-10.200.0.1}"
    local current
    current="$(awk '/^[[:space:]]*nameserver/ {printf "%s ", $2}' /etc/resolv.conf 2>/dev/null || true)"

    # Do not clobber an already-correct file.
    if [ "$current" = "${resolver} " ]; then
        log_debug "resolv.conf already points at ${resolver}"
        return 0
    fi

    log_info "Pointing the shared /etc/resolv.conf at ${resolver} (reachable from both namespaces)"
    if ! printf 'nameserver %s\noptions ndots:0\n' "$resolver" > /etc/resolv.conf 2>/dev/null; then
        log_warn "Could not write /etc/resolv.conf; DNS may be broken in one of the namespaces"
        return 1
    fi
    return 0
}

# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

# Prove that name resolution works on BOTH sides of the namespace boundary.
#
# These are separate resolvers by design. After WARP connects, the shared file
# names 127.0.2.2: in the root namespace that is our stub, in the WARP namespace
# it is WARP's proxy. Both must answer, and neither may depend on the other.
#
# The root namespace is probed with a name the stub answers locally, so a
# failure here means the stub itself is broken rather than the upstream network.
# The WARP namespace is probed with a real name, because its resolver is WARP's
# own proxy and has no local records.
verify_dns() {
    local root_ok=0 warp_ok=0
    local root_ns warp_ns

    root_ns="$(awk '/^[[:space:]]*nameserver/ {printf "%s ", $2}' /etc/resolv.conf 2>/dev/null || true)"
    if [ -n "${WARP_NETNS:-}" ]; then
        warp_ns="$(ns_run awk '/^[[:space:]]*nameserver/ {printf "%s ", $2}' /etc/resolv.conf 2>/dev/null || true)"
    fi

    # Root namespace: does its own resolver answer at all?
    if getent hosts "$DNS_PROBE_NAME" >/dev/null 2>&1; then
        root_ok=1
    elif getent hosts one.one.one.one >/dev/null 2>&1; then
        root_ok=1
    fi

    if [ -z "${WARP_NETNS:-}" ]; then
        warp_ok="$root_ok"
    elif ns_run getent hosts one.one.one.one >/dev/null 2>&1; then
        warp_ok=1
    fi

    log_info "DNS root namespace [${root_ns% }] : $([ "$root_ok" = 1 ] && echo ok || echo FAILED)"
    if [ -n "${WARP_NETNS:-}" ]; then
        log_info "DNS warp namespace [${warp_ns% }] : $([ "$warp_ok" = 1 ] && echo ok || echo FAILED)"
    fi

    if [ "$root_ok" != 1 ]; then
        log_error "The container's own resolver does not answer. Once WARP rewrites"
        log_error "/etc/resolv.conf to 127.0.2.2, DNS dies for tailscaled unless a"
        log_error "stub resolver listens there in the root namespace."
        if ! command -v dnsmasq >/dev/null 2>&1; then
            log_error "dnsmasq is not installed, so the stub could not be started."
        fi
    fi

    if [ "$root_ok" != 1 ] || [ "$warp_ok" != 1 ]; then
        return 1
    fi
    return 0
}
